### ISSUE TITLE
The request has been black-holed

### ISSUE THREAD

**Issue by troscoe** [Zuluru/Zuluru3#41]
Having issues completing the initial admin user profile. Was able to complete it by modifying the database directly however, issue persists when trying to create a new user. No other issues with POST requests.

OS: Ubuntu 22.04
Webserver: Nginx
PHP: 7.4.3
MySQL: 5.7.41 (AWS RDS with custom parameters group my_sql = NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION)
SSL terminated at AWS load balancer

`server {
        listen 80 default_server;
        listen [::]:80 default_server;

        # SSL configuration
        #
        # listen 443 ssl default_server;
        # listen [::]:443 ssl default_server;
        #
        # Note: You should disable gzip for SSL traffic.
        # See: https://bugs.debian.org/773332
        #
        # Read up on ssl_ciphers to ensure a secure configuration.
        # See: https://bugs.debian.org/765782
        #
        # Self signed certs generated by the ssl-cert package
        # Don't use them in a production server!
        #
        # include snippets/snakeoil.conf;

        root /var/www/html/Zuluru3/webroot;

        # Add index.php to the list if you are using PHP
        index index.php index.html index.htm index.nginx-debian.html;

        access_log /var/www/html/Zuluru3/logs/access.log;
        error_log /var/www/html/Zuluru3/logs/error.log;

        server_name _;

        location / {
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.
                #try_files $uri $uri/ =404;
                try_files $uri $uri/ /index.php?$args;
        }

        # pass PHP scripts to FastCGI server
        #
        location ~ \.php$ {
                include snippets/fastcgi-php.conf;
        #
        #       # With php-fpm (or other unix sockets):
                fastcgi_pass unix:/run/php/php7.4-fpm.sock;
        #       # With php-cgi (or other tcp sockets):
        #       fastcgi_pass 127.0.0.1:9000;
        }

        # deny access to .htaccess files, if Apache's document root
        # concurs with nginx's one
        #
        location ~ /\.ht {
                deny all;
        }
}`

Error log when trying to save initial admin user:
`2023-04-12 16:46:47 Error: [Cake\Http\Exception\BadRequestException] The request has been black-holed (/var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Controller/Component/SecurityComponent.php:611)
#0 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Controller/Component/SecurityComponent.php(195): Cake\Controller\Component\SecurityComponent->_callback()
#1 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Controller/Component/SecurityComponent.php(127): Cake\Controller\Component\SecurityComponent->blackHole()
#2 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Event/EventManager.php(352): Cake\Controller\Component\SecurityComponent->startup()
#3 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Event/EventManager.php(329): Cake\Event\EventManager->_callListener()
#4 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Event/EventDispatcherTrait.php(113): Cake\Event\EventManager->dispatch()
#5 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Controller/Controller.php(680): Cake\Controller\Controller->dispatchEvent()
#6 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(115): Cake\Controller\Controller->startupProcess()
#7 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(94): Cake\Http\ActionDispatcher->_invoke()
#8 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Http/BaseApplication.php(234): Cake\Http\ActionDispatcher->dispatch()
#9 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Http\BaseApplication->__invoke()
#10 /var/www/html/Zuluru3/src/Middleware/AffiliateConfigurationLoader.php(19): Cake\Http\Runner->__invoke()
#11 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Http/Runner.php(65): App\Middleware\AffiliateConfigurationLoader->__invoke()
#12 /var/www/html/Zuluru3/src/Http/Middleware/ActAsMiddleware.php(56): Cake\Http\Runner->__invoke()
#13 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Http/Runner.php(65): App\Http\Middleware\ActAsMiddleware->__invoke()
#14 /var/www/html/Zuluru3/vendor/cakephp/authorization/src/Middleware/AuthorizationMiddleware.php(113): Cake\Http\Runner->__invoke()
#15 /var/www/html/Zuluru3/src/Application.php(532): Authorization\Middleware\AuthorizationMiddleware->__invoke()
#16 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Http/Runner.php(65): App\Application->App\{closure}()
#17 /var/www/html/Zuluru3/src/Middleware/LocalizationMiddleware.php(176): Cake\Http\Runner->__invoke()
#18 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Http/Runner.php(65): App\Middleware\LocalizationMiddleware->__invoke()
#19 /var/www/html/Zuluru3/src/Application.php(465): Cake\Http\Runner->__invoke()
#20 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Http/Runner.php(65): App\Application->App\{closure}()
#21 /var/www/html/Zuluru3/src/Application.php(431): Cake\Http\Runner->__invoke()
#22 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Http/Runner.php(65): App\Application->App\{closure}()
#23 /var/www/html/Zuluru3/vendor/cakephp/authentication/src/Middleware/AuthenticationMiddleware.php(116): Cake\Http\Runner->__invoke()
#24 /var/www/html/Zuluru3/src/Application.php(418): Authentication\Middleware\AuthenticationMiddleware->__invoke()
#25 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Http/Runner.php(65): App\Application->App\{closure}()
#26 /var/www/html/Zuluru3/vendor/dereuromark/cakephp-ajax/src/Middleware/AjaxMiddleware.php(72): Cake\Http\Runner->__invoke()
#27 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Http/Runner.php(65): Ajax\Middleware\AjaxMiddleware->__invoke()
#28 /var/www/html/Zuluru3/src/Http/Middleware/CookiePathMiddleware.php(33): Cake\Http\Runner->__invoke()
#29 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Http/Runner.php(65): App\Http\Middleware\CookiePathMiddleware->__invoke()
#30 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Http/Middleware/EncryptedCookieMiddleware.php(89): Cake\Http\Runner->__invoke()
#31 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Http\Middleware\EncryptedCookieMiddleware->__invoke()
#32 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Http/Middleware/CsrfProtectionMiddleware.php(124): Cake\Http\Runner->__invoke()
#33 /var/www/html/Zuluru3/src/Application.php(383): Cake\Http\Middleware\CsrfProtectionMiddleware->__invoke()
#34 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Http/Runner.php(65): App\Application->App\{closure}()
#35 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Http/Middleware/BodyParserMiddleware.php(140): Cake\Http\Runner->__invoke()
#36 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Http\Middleware\BodyParserMiddleware->__invoke()
#37 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Routing/Middleware/RoutingMiddleware.php(162): Cake\Http\Runner->__invoke()
#38 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke()
#39 /var/www/html/Zuluru3/vendor/ozee31/cakephp-cors/src/Routing/Middleware/CorsMiddleware.php(32): Cake\Http\Runner->__invoke()
#40 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cors\Routing\Middleware\CorsMiddleware->__invoke()
#41 /var/www/html/Zuluru3/src/Middleware/LocalizationMiddleware.php(176): Cake\Http\Runner->__invoke()
#42 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Http/Runner.php(65): App\Middleware\LocalizationMiddleware->__invoke()
#43 /var/www/html/Zuluru3/src/Middleware/LocalizationMiddleware.php(176): Cake\Http\Runner->__invoke()
#44 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Http/Runner.php(65): App\Middleware\LocalizationMiddleware->__invoke()
#45 /var/www/html/Zuluru3/src/Middleware/ConfigurationLoader.php(19): Cake\Http\Runner->__invoke()
#46 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Http/Runner.php(65): App\Middleware\ConfigurationLoader->__invoke()
#47 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Routing/Middleware/AssetMiddleware.php(88): Cake\Http\Runner->__invoke()
#48 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke()
#49 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Error/Middleware/ErrorHandlerMiddleware.php(96): Cake\Http\Runner->__invoke()
#50 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke()
#51 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Http/Runner.php(51): Cake\Http\Runner->__invoke()
#52 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Http/Server.php(97): Cake\Http\Runner->run()
#53 /var/www/html/Zuluru3/webroot/index.php(41): Cake\Http\Server->run()
#54 {main}
Request URL: /people/edit`

Error log when trying to create new user:
`2023-04-12 16:55:08 Error: [Cake\Http\Exception\BadRequestException] The request has been black-holed (/var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Controller/Component/SecurityComponent.php:611)
#0 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Controller/Component/SecurityComponent.php(195): Cake\Controller\Component\SecurityComponent->_callback()
#1 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Controller/Component/SecurityComponent.php(127): Cake\Controller\Component\SecurityComponent->blackHole()
#2 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Event/EventManager.php(352): Cake\Controller\Component\SecurityComponent->startup()
#3 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Event/EventManager.php(329): Cake\Event\EventManager->_callListener()
#4 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Event/EventDispatcherTrait.php(113): Cake\Event\EventManager->dispatch()
#5 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Controller/Controller.php(680): Cake\Controller\Controller->dispatchEvent()
#6 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(115): Cake\Controller\Controller->startupProcess()
#7 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(94): Cake\Http\ActionDispatcher->_invoke()
#8 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Http/BaseApplication.php(234): Cake\Http\ActionDispatcher->dispatch()
#9 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Http\BaseApplication->__invoke()
#10 /var/www/html/Zuluru3/src/Middleware/AffiliateConfigurationLoader.php(19): Cake\Http\Runner->__invoke()
#11 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Http/Runner.php(65): App\Middleware\AffiliateConfigurationLoader->__invoke()
#12 /var/www/html/Zuluru3/src/Http/Middleware/ActAsMiddleware.php(56): Cake\Http\Runner->__invoke()
#13 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Http/Runner.php(65): App\Http\Middleware\ActAsMiddleware->__invoke()
#14 /var/www/html/Zuluru3/vendor/cakephp/authorization/src/Middleware/AuthorizationMiddleware.php(113): Cake\Http\Runner->__invoke()
#15 /var/www/html/Zuluru3/src/Application.php(532): Authorization\Middleware\AuthorizationMiddleware->__invoke()
#16 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Http/Runner.php(65): App\Application->App\{closure}()
#17 /var/www/html/Zuluru3/src/Middleware/LocalizationMiddleware.php(176): Cake\Http\Runner->__invoke()
#18 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Http/Runner.php(65): App\Middleware\LocalizationMiddleware->__invoke()
#19 /var/www/html/Zuluru3/src/Application.php(465): Cake\Http\Runner->__invoke()
#20 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Http/Runner.php(65): App\Application->App\{closure}()
#21 /var/www/html/Zuluru3/src/Application.php(431): Cake\Http\Runner->__invoke()
#22 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Http/Runner.php(65): App\Application->App\{closure}()
#23 /var/www/html/Zuluru3/vendor/cakephp/authentication/src/Middleware/AuthenticationMiddleware.php(116): Cake\Http\Runner->__invoke()
#24 /var/www/html/Zuluru3/src/Application.php(418): Authentication\Middleware\AuthenticationMiddleware->__invoke()
#25 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Http/Runner.php(65): App\Application->App\{closure}()
#26 /var/www/html/Zuluru3/vendor/dereuromark/cakephp-ajax/src/Middleware/AjaxMiddleware.php(72): Cake\Http\Runner->__invoke()
#27 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Http/Runner.php(65): Ajax\Middleware\AjaxMiddleware->__invoke()
#28 /var/www/html/Zuluru3/src/Http/Middleware/CookiePathMiddleware.php(33): Cake\Http\Runner->__invoke()
#29 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Http/Runner.php(65): App\Http\Middleware\CookiePathMiddleware->__invoke()
#30 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Http/Middleware/EncryptedCookieMiddleware.php(89): Cake\Http\Runner->__invoke()
#31 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Http\Middleware\EncryptedCookieMiddleware->__invoke()
#32 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Http/Middleware/CsrfProtectionMiddleware.php(124): Cake\Http\Runner->__invoke()
#33 /var/www/html/Zuluru3/src/Application.php(383): Cake\Http\Middleware\CsrfProtectionMiddleware->__invoke()
#34 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Http/Runner.php(65): App\Application->App\{closure}()
#35 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Http/Middleware/BodyParserMiddleware.php(140): Cake\Http\Runner->__invoke()
#36 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Http\Middleware\BodyParserMiddleware->__invoke()
#37 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Routing/Middleware/RoutingMiddleware.php(162): Cake\Http\Runner->__invoke()
#38 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke()
#39 /var/www/html/Zuluru3/vendor/ozee31/cakephp-cors/src/Routing/Middleware/CorsMiddleware.php(32): Cake\Http\Runner->__invoke()
#40 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cors\Routing\Middleware\CorsMiddleware->__invoke()
#41 /var/www/html/Zuluru3/src/Middleware/LocalizationMiddleware.php(176): Cake\Http\Runner->__invoke()
#42 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Http/Runner.php(65): App\Middleware\LocalizationMiddleware->__invoke()
#43 /var/www/html/Zuluru3/src/Middleware/LocalizationMiddleware.php(176): Cake\Http\Runner->__invoke()
#44 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Http/Runner.php(65): App\Middleware\LocalizationMiddleware->__invoke()
#45 /var/www/html/Zuluru3/src/Middleware/ConfigurationLoader.php(19): Cake\Http\Runner->__invoke()
#46 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Http/Runner.php(65): App\Middleware\ConfigurationLoader->__invoke()
#47 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Routing/Middleware/AssetMiddleware.php(88): Cake\Http\Runner->__invoke()
#48 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke()
#49 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Error/Middleware/ErrorHandlerMiddleware.php(96): Cake\Http\Runner->__invoke()
#50 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke()
#51 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Http/Runner.php(51): Cake\Http\Runner->__invoke()
#52 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Http/Server.php(97): Cake\Http\Runner->run()
#53 /var/www/html/Zuluru3/webroot/index.php(41): Cake\Http\Server->run()
#54 {main}
Request URL: /users/create_account`

**Comment by Zuluru** [comment]
The black hole usually happens only if the form was open for quite a while before hitting "submit". Is that the case here, or does it still happen if you fill the form out quickly?

If you are okay with skipping this security check, you can add
`$this->Security->config('validatePost', false);`
right after the line
`$this->loadComponent('Security');`
in `src/Controller/AppController.php`.

**Comment by troscoe** [comment]
It happens even if I submit a few seconds after initial page load.

Skipping the security check by adding the line you suggested does "resolve" the issue.

Any additional information I can provide that would be useful to you?

**Comment by Zuluru** [comment]
Not at this time, thanks. I already have a todo item on my list to revisit that particular functionality and its general benefit.
