### ISSUE TITLE
Edit people Black Hole

### ISSUE THREAD

**Issue by alexlarraga1** [Zuluru/Zuluru3#44]
When update the Admin user after install, gemerates next error

`
2023-08-30 21:40:16 Error: [Cake\Http\Exception\BadRequestException] The request has been black-holed (D:\DEV\SPORT MANAGER\Zuluru3\vendor\cakephp\cakephp\src\Controller\Component\SecurityComponent.php:616)
#0 D:\DEV\SPORT MANAGER\Zuluru3\vendor\cakephp\cakephp\src\Controller\Component\SecurityComponent.php(197): Cake\Controller\Component\SecurityComponent->_callback(Object(App\Controller\PeopleController), '_blackhole', Array)
#1 D:\DEV\SPORT MANAGER\Zuluru3\vendor\cakephp\cakephp\src\Controller\Component\SecurityComponent.php(129): Cake\Controller\Component\SecurityComponent->blackHole(Object(App\Controller\PeopleController), 'auth', Object(Cake\Controller\Exception\AuthSecurityException))
#2 D:\DEV\SPORT MANAGER\Zuluru3\vendor\cakephp\cakephp\src\Event\EventManager.php(351): Cake\Controller\Component\SecurityComponent->startup(Object(Cake\Event\Event))
#3 D:\DEV\SPORT MANAGER\Zuluru3\vendor\cakephp\cakephp\src\Event\EventManager.php(328): Cake\Event\EventManager->_callListener(Array, Object(Cake\Event\Event))
#4 D:\DEV\SPORT MANAGER\Zuluru3\vendor\cakephp\cakephp\src\Event\EventDispatcherTrait.php(112): Cake\Event\EventManager->dispatch(Object(Cake\Event\Event))
#5 D:\DEV\SPORT MANAGER\Zuluru3\vendor\cakephp\cakephp\src\Controller\Controller.php(677): Cake\Controller\Controller->dispatchEvent('Controller.star...')
#6 D:\DEV\SPORT MANAGER\Zuluru3\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(115): Cake\Controller\Controller->startupProcess()
#7 D:\DEV\SPORT MANAGER\Zuluru3\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(94): Cake\Http\ActionDispatcher->_invoke(Object(App\Controller\PeopleController))
#8 D:\DEV\SPORT MANAGER\Zuluru3\vendor\cakephp\cakephp\src\Http\BaseApplication.php(256): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#9 D:\DEV\SPORT MANAGER\Zuluru3\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#10 D:\DEV\SPORT MANAGER\Zuluru3\src\Middleware\AffiliateConfigurationLoader.php(19): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#11 D:\DEV\SPORT MANAGER\Zuluru3\vendor\cakephp\cakephp\src\Http\Runner.php(65): App\Middleware\AffiliateConfigurationLoader->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#12 D:\DEV\SPORT MANAGER\Zuluru3\src\Http\Middleware\ActAsMiddleware.php(56): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#13 D:\DEV\SPORT MANAGER\Zuluru3\vendor\cakephp\cakephp\src\Http\Runner.php(65): App\Http\Middleware\ActAsMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#14 D:\DEV\SPORT MANAGER\Zuluru3\vendor\cakephp\authorization\src\Middleware\AuthorizationMiddleware.php(113): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#15 D:\DEV\SPORT MANAGER\Zuluru3\src\Application.php(532): Authorization\Middleware\AuthorizationMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#16 D:\DEV\SPORT MANAGER\Zuluru3\vendor\cakephp\cakephp\src\Http\Runner.php(65): App\Application->App\{closure}(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#17 D:\DEV\SPORT MANAGER\Zuluru3\src\Middleware\LocalizationMiddleware.php(176): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#18 D:\DEV\SPORT MANAGER\Zuluru3\vendor\cakephp\cakephp\src\Http\Runner.php(65): App\Middleware\LocalizationMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#19 D:\DEV\SPORT MANAGER\Zuluru3\src\Application.php(465): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#20 D:\DEV\SPORT MANAGER\Zuluru3\vendor\cakephp\cakephp\src\Http\Runner.php(65): App\Application->App\{closure}(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#21 D:\DEV\SPORT MANAGER\Zuluru3\src\Application.php(431): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#22 D:\DEV\SPORT MANAGER\Zuluru3\vendor\cakephp\cakephp\src\Http\Runner.php(65): App\Application->App\{closure}(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#23 D:\DEV\SPORT MANAGER\Zuluru3\vendor\cakephp\authentication\src\Middleware\AuthenticationMiddleware.php(116): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#24 D:\DEV\SPORT MANAGER\Zuluru3\src\Application.php(418): Authentication\Middleware\AuthenticationMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#25 D:\DEV\SPORT MANAGER\Zuluru3\vendor\cakephp\cakephp\src\Http\Runner.php(65): App\Application->App\{closure}(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#26 D:\DEV\SPORT MANAGER\Zuluru3\vendor\dereuromark\cakephp-ajax\src\Middleware\AjaxMiddleware.php(72): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#27 D:\DEV\SPORT MANAGER\Zuluru3\vendor\cakephp\cakephp\src\Http\Runner.php(65): Ajax\Middleware\AjaxMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#28 D:\DEV\SPORT MANAGER\Zuluru3\src\Http\Middleware\CookiePathMiddleware.php(33): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#29 D:\DEV\SPORT MANAGER\Zuluru3\vendor\cakephp\cakephp\src\Http\Runner.php(65): App\Http\Middleware\CookiePathMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#30 D:\DEV\SPORT MANAGER\Zuluru3\vendor\cakephp\cakephp\src\Http\Middleware\EncryptedCookieMiddleware.php(90): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#31 D:\DEV\SPORT MANAGER\Zuluru3\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\Middleware\EncryptedCookieMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#32 D:\DEV\SPORT MANAGER\Zuluru3\vendor\cakephp\cakephp\src\Http\Middleware\CsrfProtectionMiddleware.php(137): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#33 D:\DEV\SPORT MANAGER\Zuluru3\src\Application.php(383): Cake\Http\Middleware\CsrfProtectionMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#34 D:\DEV\SPORT MANAGER\Zuluru3\vendor\cakephp\cakephp\src\Http\Runner.php(65): App\Application->App\{closure}(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#35 D:\DEV\SPORT MANAGER\Zuluru3\vendor\cakephp\cakephp\src\Http\Middleware\BodyParserMiddleware.php(140): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#36 D:\DEV\SPORT MANAGER\Zuluru3\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\Middleware\BodyParserMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#37 D:\DEV\SPORT MANAGER\Zuluru3\vendor\cakephp\cakephp\src\Routing\Middleware\RoutingMiddleware.php(164): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#38 D:\DEV\SPORT MANAGER\Zuluru3\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#39 D:\DEV\SPORT MANAGER\Zuluru3\vendor\ozee31\cakephp-cors\src\Routing\Middleware\CorsMiddleware.php(32): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#40 D:\DEV\SPORT MANAGER\Zuluru3\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cors\Routing\Middleware\CorsMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#41 D:\DEV\SPORT MANAGER\Zuluru3\src\Middleware\LocalizationMiddleware.php(176): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#42 D:\DEV\SPORT MANAGER\Zuluru3\vendor\cakephp\cakephp\src\Http\Runner.php(65): App\Middleware\LocalizationMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#43 D:\DEV\SPORT MANAGER\Zuluru3\src\Middleware\LocalizationMiddleware.php(176): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#44 D:\DEV\SPORT MANAGER\Zuluru3\vendor\cakephp\cakephp\src\Http\Runner.php(65): App\Middleware\LocalizationMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#45 D:\DEV\SPORT MANAGER\Zuluru3\src\Middleware\ConfigurationLoader.php(19): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#46 D:\DEV\SPORT MANAGER\Zuluru3\vendor\cakephp\cakephp\src\Http\Runner.php(65): App\Middleware\ConfigurationLoader->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#47 D:\DEV\SPORT MANAGER\Zuluru3\vendor\cakephp\cakephp\src\Routing\Middleware\AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#48 D:\DEV\SPORT MANAGER\Zuluru3\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#49 D:\DEV\SPORT MANAGER\Zuluru3\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(100): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#50 D:\DEV\SPORT MANAGER\Zuluru3\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#51 D:\DEV\SPORT MANAGER\Zuluru3\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#52 D:\DEV\SPORT MANAGER\Zuluru3\vendor\cakephp\cakephp\src\Http\Server.php(97): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#53 D:\DEV\SPORT MANAGER\Zuluru3\webroot\index.php(41): Cake\Http\Server->run()
#54 {main}
Request URL: /people/edit
Referer URL: http://localhost:8765/people/edit
`

**Comment by Zuluru** [comment]
Apologies for the delay in responding.

Am I understanding correctly that this is after the installation has been completed, you can login successfully, but when you go to edit the admin user you get this error? Did you have the edit page open for a while before submitting it? There is a built-in security mechanism whereby edits have timestamps on them and if it's too long (15 minutes, I think) after that, then it gets blocked.
